spring:
     datasource:
              url: jdbc:mysql://localhost:3306/Spring-Boot?createDatabaseIfNotExist=true
              username: root
              password: Yasmeen@8653#
              driver-class-name: com.mysql.cj.jdbc.Driver
     mvc: 
       pathmatch :
           matching-strategy : ANT_PATH_MATCHER
     jpa:
        hibernate:
               ddl-auto: update
                  
logging:
     level:
          com:
             thoughtFocus: DEBUG
     pattern: 
           console: "%d{yyyy-MM-dd HH:mm:ss} - %m%n"

server:
    port: 8088